<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830072849 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, name_normalized VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(32) NOT NULL, type VARCHAR(16) NOT NULL, options JSON DEFAULT NULL, is_system BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, removed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA7AEFFBB03A8386 ON attribute (created_by_id)');
        $this->addSql('CREATE INDEX idx_attribute_category ON attribute (category)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_name_normalized ON attribute (name_normalized)');
        $this->addSql('CREATE TABLE attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value_string VARCHAR(255) DEFAULT NULL, value_text TEXT DEFAULT NULL, value_number NUMERIC(20, 6) DEFAULT NULL, value_date DATE DEFAULT NULL, value_date_end DATE DEFAULT NULL, value_bool BOOLEAN DEFAULT NULL, value_option VARCHAR(255) DEFAULT NULL, value_image_url VARCHAR(1024) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, profile_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE4FBB82CCFA12B8 ON attribute_value (profile_id)');
        $this->addSql('CREATE INDEX IDX_FE4FBB82B6E62EFA ON attribute_value (attribute_id)');
        $this->addSql('CREATE INDEX idx_value_attribute_number ON attribute_value (attribute_id, value_number)');
        $this->addSql('CREATE INDEX idx_value_attribute_bool ON attribute_value (attribute_id, value_bool)');
        $this->addSql('CREATE INDEX idx_value_attribute_option ON attribute_value (attribute_id, value_option)');
        $this->addSql('CREATE UNIQUE INDEX uniq_value_profile_attribute ON attribute_value (profile_id, attribute_id)');
        $this->addSql('CREATE TABLE cv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(16) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, likes_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, profile_id INT NOT NULL, position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B66FFE92CCFA12B8 ON cv (profile_id)');
        $this->addSql('CREATE INDEX IDX_B66FFE92DD842E46 ON cv (position_id)');
        $this->addSql('CREATE INDEX idx_cv_position_status ON cv (position_id, status)');
        $this->addSql('CREATE INDEX idx_cv_created_at ON cv (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_profile_position ON cv (profile_id, position_id)');
        $this->addSql('CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cv_id INT NOT NULL, recruiter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD2DA06FCFE419E2 ON cv_like (cv_id)');
        $this->addSql('CREATE INDEX IDX_CD2DA06F156BE243 ON cv_like (recruiter_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_like_cv_recruiter ON cv_like (cv_id, recruiter_id)');
        $this->addSql('CREATE TABLE discussion_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FE4C0BBDD842E46 ON discussion_post (position_id)');
        $this->addSql('CREATE INDEX IDX_7FE4C0BBF675F31B ON discussion_post (author_id)');
        $this->addSql('CREATE INDEX idx_post_position_id ON discussion_post (position_id, id)');
        $this->addSql('CREATE TABLE "position" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, short_description TEXT DEFAULT NULL, company VARCHAR(180) DEFAULT NULL, level VARCHAR(32) DEFAULT NULL, is_public BOOLEAN NOT NULL, max_projects INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_462CE4F5B03A8386 ON "position" (created_by_id)');
        $this->addSql('CREATE INDEX idx_position_public ON "position" (is_public)');
        $this->addSql('CREATE TABLE position_tag (position_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (position_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_F73FBF9BDD842E46 ON position_tag (position_id)');
        $this->addSql('CREATE INDEX IDX_F73FBF9BBAD26311 ON position_tag (tag_id)');
        $this->addSql('CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operator VARCHAR(16) NOT NULL, operand_string VARCHAR(255) DEFAULT NULL, operand_number NUMERIC(20, 6) DEFAULT NULL, operand_date DATE DEFAULT NULL, operand_bool BOOLEAN DEFAULT NULL, operand_options JSON DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D97A8C6DD842E46 ON position_access_rule (position_id)');
        $this->addSql('CREATE INDEX idx_access_rule_attribute ON position_access_rule (attribute_id)');
        $this->addSql('CREATE TABLE position_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sort_order INT NOT NULL, section VARCHAR(120) DEFAULT NULL, required BOOLEAN NOT NULL, removed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF5BEE86DD842E46 ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_AF5BEE86B6E62EFA ON position_attribute (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_attribute ON position_attribute (position_id, attribute_id)');
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version INT DEFAULT 1 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8157AA0FA76ED395 ON profile (user_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, period_from DATE DEFAULT NULL, period_to DATE DEFAULT NULL, description TEXT DEFAULT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EECCFA12B8 ON project (profile_id)');
        $this->addSql('CREATE INDEX idx_project_profile_order ON project (profile_id, sort_order)');
        $this->addSql('CREATE TABLE project_tag (project_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (project_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_91F26D60166D1F9C ON project_tag (project_id)');
        $this->addSql('CREATE INDEX IDX_91F26D60BAD26311 ON project_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, name_normalized VARCHAR(64) NOT NULL, usage_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tag_usage ON tag (usage_count)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_name_normalized ON tag (name_normalized)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, status VARCHAR(16) NOT NULL, locale VARCHAR(8) NOT NULL, theme VARCHAR(8) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_user_status ON "user" (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE user_identity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(32) NOT NULL, external_id VARCHAR(191) NOT NULL, linked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A180DC4A76ED395 ON user_identity (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_identity_provider_external ON user_identity (provider, external_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_identity_user_provider ON user_identity (user_id, provider)');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFBB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB82CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB82B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE92CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE92DD842E46 FOREIGN KEY (position_id) REFERENCES "position" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06FCFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06F156BE243 FOREIGN KEY (recruiter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_7FE4C0BBDD842E46 FOREIGN KEY (position_id) REFERENCES "position" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_7FE4C0BBF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "position" ADD CONSTRAINT FK_462CE4F5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_tag ADD CONSTRAINT FK_F73FBF9BDD842E46 FOREIGN KEY (position_id) REFERENCES "position" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_tag ADD CONSTRAINT FK_F73FBF9BBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6DD842E46 FOREIGN KEY (position_id) REFERENCES "position" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86DD842E46 FOREIGN KEY (position_id) REFERENCES "position" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EECCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_identity ADD CONSTRAINT FK_8A180DC4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute DROP CONSTRAINT FK_FA7AEFFBB03A8386');
        $this->addSql('ALTER TABLE attribute_value DROP CONSTRAINT FK_FE4FBB82CCFA12B8');
        $this->addSql('ALTER TABLE attribute_value DROP CONSTRAINT FK_FE4FBB82B6E62EFA');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92CCFA12B8');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92DD842E46');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06FCFE419E2');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06F156BE243');
        $this->addSql('ALTER TABLE discussion_post DROP CONSTRAINT FK_7FE4C0BBDD842E46');
        $this->addSql('ALTER TABLE discussion_post DROP CONSTRAINT FK_7FE4C0BBF675F31B');
        $this->addSql('ALTER TABLE "position" DROP CONSTRAINT FK_462CE4F5B03A8386');
        $this->addSql('ALTER TABLE position_tag DROP CONSTRAINT FK_F73FBF9BDD842E46');
        $this->addSql('ALTER TABLE position_tag DROP CONSTRAINT FK_F73FBF9BBAD26311');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6DD842E46');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6B6E62EFA');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86DD842E46');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86B6E62EFA');
        $this->addSql('ALTER TABLE profile DROP CONSTRAINT FK_8157AA0FA76ED395');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EECCFA12B8');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60166D1F9C');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60BAD26311');
        $this->addSql('ALTER TABLE user_identity DROP CONSTRAINT FK_8A180DC4A76ED395');
        $this->addSql('DROP TABLE attribute');
        $this->addSql('DROP TABLE attribute_value');
        $this->addSql('DROP TABLE cv');
        $this->addSql('DROP TABLE cv_like');
        $this->addSql('DROP TABLE discussion_post');
        $this->addSql('DROP TABLE "position"');
        $this->addSql('DROP TABLE position_tag');
        $this->addSql('DROP TABLE position_access_rule');
        $this->addSql('DROP TABLE position_attribute');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_tag');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_identity');
    }
}
